#include "Aetherion/Assets/AssetGenerator.h"
#include "Aetherion/Assets/LLMClient.h"

#include <fstream>
#include <sstream>
#include <chrono>
#include <regex>
#include <cstring>

#include <nlohmann/json.hpp>

namespace {

std::uint64_t GetCurrentTimeMs() {
    using namespace std::chrono;
    return duration_cast<milliseconds>(
        steady_clock::now().time_since_epoch()).count();
}

std::string ToLower(const std::string& str) {
    std::string result = str;
    std::transform(result.begin(), result.end(), result.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return result;
}

bool ContainsWord(const std::string& text, const std::string& word) {
    return ToLower(text).find(ToLower(word)) != std::string::npos;
}

// Write PNG data to file
void WritePNG(const std::filesystem::path& path, const std::vector<uint8_t>& data) {
    std::ofstream file(path, std::ios::binary);
    if (file.is_open()) {
        file.write(reinterpret_cast<const char*>(data.data()), 
                   static_cast<std::streamsize>(data.size()));
    }
}

// Write OBJ mesh file
void WriteOBJ(const std::filesystem::path& path,
              const std::vector<std::array<float, 3>>& vertices,
              const std::vector<std::array<float, 3>>& normals,
              const std::vector<std::array<float, 2>>& uvs,
              const std::vector<std::array<int, 3>>& faces) {
    std::ofstream file(path);
    if (!file.is_open()) return;
    
    file << "# Generated by Aetherion LLM Asset Generator\n\n";
    
    for (const auto& v : vertices) {
        file << "v " << v[0] << " " << v[1] << " " << v[2] << "\n";
    }
    file << "\n";
    
    for (const auto& n : normals) {
        file << "vn " << n[0] << " " << n[1] << " " << n[2] << "\n";
    }
    file << "\n";
    
    for (const auto& uv : uvs) {
        file << "vt " << uv[0] << " " << uv[1] << "\n";
    }
    file << "\n";
    
    for (const auto& f : faces) {
        file << "f " << (f[0] + 1) << "/" << (f[0] + 1) << "/" << (f[0] + 1)
             << " " << (f[1] + 1) << "/" << (f[1] + 1) << "/" << (f[1] + 1)
             << " " << (f[2] + 1) << "/" << (f[2] + 1) << "/" << (f[2] + 1) << "\n";
    }
}

// Write WAV audio file
void WriteWAV(const std::filesystem::path& path,
              const std::vector<int16_t>& samples,
              int sampleRate = 44100) {
    std::ofstream file(path, std::ios::binary);
    if (!file.is_open()) return;
    
    const int numChannels = 1;
    const int bitsPerSample = 16;
    const int byteRate = sampleRate * numChannels * bitsPerSample / 8;
    const int blockAlign = numChannels * bitsPerSample / 8;
    const int dataSize = static_cast<int>(samples.size()) * 2;
    const int chunkSize = 36 + dataSize;
    
    file.write("RIFF", 4);
    file.write(reinterpret_cast<const char*>(&chunkSize), 4);
    file.write("WAVE", 4);
    
    file.write("fmt ", 4);
    int fmtSize = 16;
    file.write(reinterpret_cast<const char*>(&fmtSize), 4);
    int16_t audioFormat = 1;
    file.write(reinterpret_cast<const char*>(&audioFormat), 2);
    int16_t channels = static_cast<int16_t>(numChannels);
    file.write(reinterpret_cast<const char*>(&channels), 2);
    file.write(reinterpret_cast<const char*>(&sampleRate), 4);
    file.write(reinterpret_cast<const char*>(&byteRate), 4);
    int16_t blockAlignShort = static_cast<int16_t>(blockAlign);
    file.write(reinterpret_cast<const char*>(&blockAlignShort), 2);
    int16_t bps = static_cast<int16_t>(bitsPerSample);
    file.write(reinterpret_cast<const char*>(&bps), 2);
    
    file.write("data", 4);
    file.write(reinterpret_cast<const char*>(&dataSize), 4);
    file.write(reinterpret_cast<const char*>(samples.data()), dataSize);
}

} // anonymous namespace

namespace Aetherion::Assets {

/// @brief LLM-powered asset generator
///
/// Uses real AI APIs (OpenAI, Anthropic, Stability AI) to generate assets
/// from natural language prompts.
class LLMAssetGenerator : public IAssetGenerator {
public:
    LLMAssetGenerator();
    ~LLMAssetGenerator() override = default;

    [[nodiscard]] std::string GetName() const override {
        return "LLMAssetGenerator";
    }

    [[nodiscard]] std::vector<std::string> GetSupportedTypes() const override {
        return {"texture", "mesh", "script"};
    }

    [[nodiscard]] bool SupportsType(const std::string& assetType) const override {
        return assetType == "texture" || assetType == "mesh" || assetType == "script";
    }

    [[nodiscard]] bool IsAvailable() const override;
    
    [[nodiscard]] std::string GetDescription() const override {
        return "AI-powered asset generator using LLM APIs (OpenAI, Anthropic, Stability AI)";
    }

    [[nodiscard]] GenerationResult Generate(const GenerationRequest& request) override;

    [[nodiscard]] std::uint64_t EstimateTimeMs(const GenerationRequest& request) const override;

    /// @brief Configure the LLM client
    void SetConfig(const LLMConfig& config);
    
    /// @brief Get the current configuration
    [[nodiscard]] const LLMConfig& GetConfig() const { return m_config; }
    
    /// @brief Set a separate image generation client (e.g., Stability AI)
    void SetImageClient(std::unique_ptr<ILLMClient> client);

private:
    GenerationResult GenerateTexture(const GenerationRequest& request);
    GenerationResult GenerateMesh(const GenerationRequest& request);
    GenerationResult GenerateScript(const GenerationRequest& request);
    
    // Parse mesh data from LLM JSON response
    bool ParseMeshFromJSON(const std::string& json,
                          std::vector<std::array<float, 3>>& vertices,
                          std::vector<std::array<float, 3>>& normals,
                          std::vector<std::array<float, 2>>& uvs,
                          std::vector<std::array<int, 3>>& faces);

    LLMConfig m_config;
    std::unique_ptr<ILLMClient> m_textClient;
    std::unique_ptr<ILLMClient> m_imageClient;
};

LLMAssetGenerator::LLMAssetGenerator() {
    // Default to OpenAI
    m_config.provider = LLMProvider::OpenAI;
    m_config.endpoint = LLMConfig::GetDefaultEndpoint(LLMProvider::OpenAI);
    m_config.model = LLMConfig::GetDefaultModel(LLMProvider::OpenAI);
    m_config.imageModel = LLMConfig::GetDefaultImageModel(LLMProvider::OpenAI);
}

bool LLMAssetGenerator::IsAvailable() const {
    return m_textClient && m_textClient->IsReady();
}

void LLMAssetGenerator::SetConfig(const LLMConfig& config) {
    m_config = config;
    m_textClient = LLMClientFactory::Create(config);
    
    // If the primary provider doesn't support images, use OpenAI DALL-E as fallback
    if (config.provider == LLMProvider::Anthropic) {
        LLMConfig imageConfig;
        imageConfig.provider = LLMProvider::OpenAI;
        imageConfig.apiKey = config.apiKey;  // Assume same key or configure separately
        m_imageClient = LLMClientFactory::Create(imageConfig);
    } else {
        m_imageClient = nullptr;  // Use text client for images
    }
}

void LLMAssetGenerator::SetImageClient(std::unique_ptr<ILLMClient> client) {
    m_imageClient = std::move(client);
}

std::uint64_t LLMAssetGenerator::EstimateTimeMs(const GenerationRequest& request) const {
    if (request.assetType == "texture") {
        return 15000;  // ~15 seconds for image generation
    } else if (request.assetType == "mesh") {
        return 10000;  // ~10 seconds for mesh generation via LLM
    } else if (request.assetType == "script") {
        return 5000;   // ~5 seconds for script generation
    }
    return 10000;
}

GenerationResult LLMAssetGenerator::Generate(const GenerationRequest& request) {
    if (!IsAvailable()) {
        GenerationResult result;
        result.success = false;
        result.message = "LLM client not configured. Please set API key in settings.";
        return result;
    }
    
    auto startTime = GetCurrentTimeMs();
    GenerationResult result;
    
    if (request.assetType == "texture") {
        result = GenerateTexture(request);
    } else if (request.assetType == "mesh") {
        result = GenerateMesh(request);
    } else if (request.assetType == "script") {
        result = GenerateScript(request);
    } else {
        result.success = false;
        result.message = "Unsupported asset type: " + request.assetType;
    }
    
    result.generationTimeMs = GetCurrentTimeMs() - startTime;
    return result;
}

GenerationResult LLMAssetGenerator::GenerateTexture(const GenerationRequest& request) {
    GenerationResult result;
    result.assetId = request.targetId.empty() ?
        ("ai_texture_" + request.requestId) : request.targetId;
    
    // Use image client if available, otherwise text client
    ILLMClient* imageClient = m_imageClient ? m_imageClient.get() : m_textClient.get();
    
    if (!imageClient || !imageClient->IsReady()) {
        result.success = false;
        result.message = "Image generation client not available";
        return result;
    }
    
    // Enhance the prompt for better texture generation
    std::string enhancedPrompt = request.prompt;
    if (!ContainsWord(enhancedPrompt, "texture") && 
        !ContainsWord(enhancedPrompt, "seamless") &&
        !ContainsWord(enhancedPrompt, "tileable")) {
        enhancedPrompt = "Seamless tileable texture: " + enhancedPrompt;
    }
    enhancedPrompt += ". High quality, 4K texture, game-ready, seamless edges.";
    
    LLMImageRequest imgRequest;
    imgRequest.prompt = enhancedPrompt;
    imgRequest.width = request.width;
    imgRequest.height = request.height;
    imgRequest.numImages = 1;
    imgRequest.quality = "hd";
    imgRequest.style = "natural";
    
    auto response = imageClient->GenerateImage(imgRequest);
    
    if (response.success && !response.images.empty()) {
        std::filesystem::path outPath = request.outputDir / (result.assetId + ".png");
        WritePNG(outPath, response.images[0]);
        
        result.success = true;
        result.outputPath = outPath;
        result.message = "Generated AI texture from prompt";
        result.diagnostics = "Prompt: " + request.prompt;
        if (!response.revisedPrompt.empty()) {
            result.diagnostics += "\nRevised prompt: " + response.revisedPrompt;
        }
        result.diagnostics += "\nLatency: " + std::to_string(response.latencyMs) + "ms";
    } else {
        result.success = false;
        result.message = "Image generation failed: " + response.errorMessage;
    }
    
    return result;
}

GenerationResult LLMAssetGenerator::GenerateMesh(const GenerationRequest& request) {
    GenerationResult result;
    result.assetId = request.targetId.empty() ?
        ("ai_mesh_" + request.requestId) : request.targetId;
    
    // Use LLM to generate mesh data as JSON
    std::string systemPrompt = R"(You are a 3D mesh generator. Given a description, generate a simple low-poly 3D mesh.
Output ONLY valid JSON in this exact format:
{
    "vertices": [[x,y,z], ...],
    "normals": [[nx,ny,nz], ...],
    "uvs": [[u,v], ...],
    "faces": [[v0,v1,v2], ...]
}

Rules:
- Vertices are in the range -1 to 1 for each axis
- Normals should be unit vectors
- UVs are in range 0 to 1
- Faces are triangles with 0-based vertex indices
- Keep it simple (under 100 vertices for basic shapes)
- For complex objects, create a simplified low-poly version)";

    std::string userPrompt = "Generate a 3D mesh for: " + request.prompt;
    
    auto response = m_textClient->GenerateJSON(systemPrompt, userPrompt);
    
    if (response.success) {
        std::vector<std::array<float, 3>> vertices;
        std::vector<std::array<float, 3>> normals;
        std::vector<std::array<float, 2>> uvs;
        std::vector<std::array<int, 3>> faces;
        
        if (ParseMeshFromJSON(response.content, vertices, normals, uvs, faces)) {
            std::filesystem::path outPath = request.outputDir / (result.assetId + ".obj");
            WriteOBJ(outPath, vertices, normals, uvs, faces);
            
            result.success = true;
            result.outputPath = outPath;
            result.message = "Generated AI mesh from prompt";
            result.diagnostics = "Vertices: " + std::to_string(vertices.size()) + 
                               ", Faces: " + std::to_string(faces.size());
        } else {
            result.success = false;
            result.message = "Failed to parse mesh data from LLM response";
            result.diagnostics = "Response: " + response.content;
        }
    } else {
        result.success = false;
        result.message = "Mesh generation failed: " + response.errorMessage;
    }
    
    return result;
}

GenerationResult LLMAssetGenerator::GenerateScript(const GenerationRequest& request) {
    GenerationResult result;
    result.assetId = request.targetId.empty() ?
        ("ai_script_" + request.requestId) : request.targetId;
    
    std::string systemPrompt = R"(You are a game behavior script generator for the Aetherion engine.
Generate Python scripts that implement game behaviors.

The script should define these functions:
- on_start(entity, context): Called when entity is created
- on_update(entity, context, delta_time): Called every frame
- on_destroy(entity, context): Called when entity is destroyed

Available context methods:
- context.get_transform(entity) -> returns position, rotation, scale
- context.set_position(entity, x, y, z)
- context.set_rotation(entity, rx, ry, rz)
- context.get_input() -> returns input state
- context.play_sound(sound_id)
- context.spawn_entity(prefab_id)
- context.get_entities_in_radius(position, radius)
- context.raycast(origin, direction, max_distance)

Output ONLY the Python code, no markdown formatting.)";

    std::string userPrompt = "Generate a behavior script for: " + request.prompt;
    
    LLMTextRequest textRequest;
    textRequest.systemPrompt = systemPrompt;
    textRequest.userPrompt = userPrompt;
    textRequest.temperature = 0.7f;
    textRequest.maxTokens = 2048;
    
    auto response = m_textClient->GenerateText(textRequest);
    
    if (response.success) {
        // Clean up the response (remove markdown code blocks if present)
        std::string code = response.content;
        
        // Remove ```python and ``` markers
        std::regex codeBlockRegex(R"(```(?:python)?\s*\n?([\s\S]*?)\n?```)");
        std::smatch match;
        if (std::regex_search(code, match, codeBlockRegex)) {
            code = match[1].str();
        }
        
        std::filesystem::path outPath = request.outputDir / (result.assetId + ".py");
        std::ofstream file(outPath);
        if (file.is_open()) {
            file << "# Auto-generated by Aetherion AI\n";
            file << "# Prompt: " << request.prompt << "\n\n";
            file << code;
        }
        
        result.success = true;
        result.outputPath = outPath;
        result.message = "Generated AI script from prompt";
        result.diagnostics = "Tokens used: " + std::to_string(response.promptTokens + response.completionTokens);
    } else {
        result.success = false;
        result.message = "Script generation failed: " + response.errorMessage;
    }
    
    return result;
}

bool LLMAssetGenerator::ParseMeshFromJSON(
    const std::string& json,
    std::vector<std::array<float, 3>>& vertices,
    std::vector<std::array<float, 3>>& normals,
    std::vector<std::array<float, 2>>& uvs,
    std::vector<std::array<int, 3>>& faces) {
    
    try {
        // Find JSON in the response (might be wrapped in markdown)
        std::string cleanJson = json;
        size_t jsonStart = json.find('{');
        size_t jsonEnd = json.rfind('}');
        if (jsonStart != std::string::npos && jsonEnd != std::string::npos) {
            cleanJson = json.substr(jsonStart, jsonEnd - jsonStart + 1);
        }
        
        auto data = nlohmann::json::parse(cleanJson);
        
        // Parse vertices
        if (data.contains("vertices")) {
            for (const auto& v : data["vertices"]) {
                if (v.is_array() && v.size() >= 3) {
                    vertices.push_back({v[0].get<float>(), v[1].get<float>(), v[2].get<float>()});
                }
            }
        }
        
        // Parse normals
        if (data.contains("normals")) {
            for (const auto& n : data["normals"]) {
                if (n.is_array() && n.size() >= 3) {
                    normals.push_back({n[0].get<float>(), n[1].get<float>(), n[2].get<float>()});
                }
            }
        }
        
        // Parse UVs
        if (data.contains("uvs")) {
            for (const auto& uv : data["uvs"]) {
                if (uv.is_array() && uv.size() >= 2) {
                    uvs.push_back({uv[0].get<float>(), uv[1].get<float>()});
                }
            }
        }
        
        // Parse faces
        if (data.contains("faces")) {
            for (const auto& f : data["faces"]) {
                if (f.is_array() && f.size() >= 3) {
                    faces.push_back({f[0].get<int>(), f[1].get<int>(), f[2].get<int>()});
                }
            }
        }
        
        // Generate default normals/uvs if not provided
        if (normals.empty()) {
            normals.resize(vertices.size(), {0.0f, 1.0f, 0.0f});
        }
        if (uvs.empty()) {
            uvs.resize(vertices.size(), {0.0f, 0.0f});
        }
        
        return !vertices.empty() && !faces.empty();
        
    } catch (const std::exception& e) {
        (void)e;
        return false;
    }
}

// =============================================================================
// Factory Registration
// =============================================================================

namespace {

struct LLMGeneratorRegistrar {
    LLMGeneratorRegistrar() {
        AssetGeneratorFactory::Instance().RegisterCreator("LLMAssetGenerator", []() {
            return std::make_shared<LLMAssetGenerator>();
        });
    }
};

static LLMGeneratorRegistrar s_registrar;

} // anonymous namespace

// Expose factory function for creating LLM generator
std::shared_ptr<IAssetGenerator> CreateLLMAssetGenerator() {
    return std::make_shared<LLMAssetGenerator>();
}

std::shared_ptr<IAssetGenerator> CreateLLMAssetGenerator(const LLMConfig& config) {
    auto generator = std::make_shared<LLMAssetGenerator>();
    generator->SetConfig(config);
    return generator;
}

} // namespace Aetherion::Assets
