# Auto-generated by Aetherion semantic scripting
# Prompt name: InlineBehavior

PROMPT = '''rotate
'''

def update(entity, context):
    """
    Stub behavior generated from PROMPT.
    Replace with model-generated logic or edit the prompt to regenerate.
    """
    return {"state": "Idle", "reason": "Stub behavior", "actions": []}
